import DiscoveryLean.PrimeModularCovariance
import DiscoveryLean.PositiveFredholmFactor
import DiscoveryLean.CayleyHardyKernel
import DiscoveryLean.PrincipalSeriesDoubling
import DiscoveryLean.FourComponentRigidity
import DiscoveryLean.CriticalBPYCoercivity
import DiscoveryLean.SchurGapTransfer
import DiscoveryLean.CasimirCriticalLine
